
exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('applications').del()
    .then(function () {
      // Inserts seed entries
      return knex('applications').insert([
        { cohort_id: 1, name: 'Ashley Collis-Burgess', email: 'ashleycollisburgess@gmail.com', phone: '(555)555-5555', address: '123s some street apt X1', city: 'New York', state: 'NY', zip: '12345', birth_date: new Date('Jan 13 2000').toISOString(), gender: 'female', ethnicity: 'Mixed', linkedin: 'https://www.linkedin.com/in/ashleycollis/', github: 'https://github.com/ashleycollis', extra_link: 'https://google.com', cover_letter: 'Lorem Ipsum', highest_degree: 'Bachelor\'s degree', college_major: 'Some major', college_location: 'New York, NY', is_employed: false, employer: '', is_military: false, income: '$55,000 to $99,000', has_laptop: true, why_interested: 'because reasons', how_heard: 'Google sent me', skill_level: 'Intermediate', app_status: 'Under review', reviewer_comments: 'Strong candidate' },
        { cohort_id: 1, name: 'Jennie Wong', email: 'jenniescwong@gmail.com', phone: '(203)810-9782', address: '123s some street apt X1', city: 'Queens', state: 'NY', zip: '12345', birth_date: new Date('Mar 01 2000').toISOString(), gender: 'female', ethnicity: 'Asian', linkedin: 'https://www.linkedin.com/in/jennie-s-c-wong/', github: 'https://github.com/jencwong', extra_link: 'https://google.com', cover_letter: 'Lorem Ipsum', highest_degree: 'Master\'s degree', college_major: 'Business Administration', college_location: 'New York, NY', is_employed: false, employer: '', is_military: false, income: '$55,000 to $99,000', has_laptop: true, why_interested: 'because reasons', how_heard: 'Google sent me', skill_level: 'Intermediate', app_status: 'Under review', reviewer_comments: 'Strong candidate' },
        { cohort_id: 1, name: 'John Fajardo', email: 'fajardocj@gmail.com', phone: '(917)539-3093', address: '3230 Steuben Ave apt G3', city: 'Bronx', state: 'NY', zip: '10467', birth_date: new Date('Apr 21 1985').toISOString(), gender: 'male', ethnicity: 'Hispanic', linkedin: 'https://www.linkedin.com/in/thatjohnfajardo/', github: 'https://github.com/thatjohn', extra_link: 'https://google.com', cover_letter: 'Lorem Ipsum', highest_degree: 'Bachelor\'s degree', college_major: 'Journalism/Media studies', college_location: 'Caracas, Venezuela', is_employed: false, employer: '', is_military: false, income: '$0 to $0', has_laptop: true, why_interested: 'I have a strong passion for being able to afford food.', how_heard: 'Some dude reached out on LinkedIn and I never saw him again.', skill_level: 'Intermediate', app_status: 'rejected', reviewer_comments: 'Dude is stupid.' },
        { cohort_id: 2, name: 'Some Guy', email: 'someguy@gmail.com', phone: '(555)555-5555', address: '123s some street apt X1', city: 'New York', state: 'NY', zip: '12345', birth_date: new Date('Jan 01 2000').toISOString(), gender: 'male', ethnicity: 'Alien', linkedin: 'https://www.linkedin.com/in/someguy/', github: 'https://github.com/someguy', extra_link: 'https://google.com', cover_letter: 'Lorem Ipsum', highest_degree: 'Bachelor\'s degree', college_major: 'Liberal Arts', college_location: 'New York, NY', is_employed: false, employer: '', is_military: true, income: '$0 to $0', has_laptop: true, why_interested: 'I need a job pls halp.', how_heard: 'Google sent me.', skill_level: 'Basic', app_status: 'under review', reviewer_comments: '' },
        { cohort_id: 2, name: 'Some Gilr', email: 'somegirl@gmail.com', phone: '(555)555-5555', address: '123s some street apt X1', city: 'New York', state: 'NY', zip: '12345', birth_date: new Date('Jan 01 2000').toISOString(), gender: 'male', ethnicity: 'Alien', linkedin: 'https://www.linkedin.com/in/somegirl/', github: 'https://github.com/somegirl', extra_link: 'https://google.com', cover_letter: 'Lorem Ipsum', highest_degree: 'Bachelor\'s degree', college_major: 'Liberal Arts', college_location: 'New York, NY', is_employed: false, employer: '', is_military: true, income: '$0 to $0', has_laptop: true, why_interested: 'I need a job pls halp.', how_heard: 'Google sent me.', skill_level: 'Basic', app_status: 'under review', reviewer_comments: 'Weak candidate, assess further' },
        { cohort_id: 2, name: 'Some Other Guy', email: 'someotherguy@gmail.com', phone: '(555)555-5555', address: '123s some street apt X1', city: 'New York', state: 'NY', zip: '12345', birth_date: new Date('Jan 01 2000').toISOString(), gender: 'male', ethnicity: 'Alien', linkedin: 'https://www.linkedin.com/in/someotherguy/', github: 'https://github.com/someotherguy', extra_link: 'https://google.com', cover_letter: 'Lorem Ipsum', highest_degree: 'Bachelor\'s degree', college_major: 'Liberal Arts', college_location: 'New York, NY', is_employed: false, employer: '', is_military: true, income: '$0 to $0', has_laptop: true, why_interested: 'I need a job pls halp.', how_heard: 'Google sent me.', skill_level: 'Basic', app_status: 'under review', reviewer_comments: 'Strong candidate, might defer to next cohort' },
        { cohort_id: 3, name: 'Some Other Girl', email: 'someothergirl@gmail.com', phone: '(555)555-5555', address: '123s some street apt X1', city: 'New York', state: 'NY', zip: '12345', birth_date: new Date('Jan 01 2000').toISOString(), gender: 'male', ethnicity: 'Alien', linkedin: 'https://www.linkedin.com/in/someothergirl/', github: 'https://github.com/someothergirl', extra_link: 'https://google.com', cover_letter: 'Lorem Ipsum', highest_degree: 'Bachelor\'s degree', college_major: 'Liberal Arts', college_location: 'New York, NY', is_employed: false, employer: '', is_military: true, income: '$0 to $0', has_laptop: true, why_interested: 'I need a job pls halp.', how_heard: 'Google sent me.', skill_level: 'Basic', app_status: 'approved', reviewer_comments: '' },
      ]);
    });
};