let dummyData =
  {
    "name": "Paul",
    "phone": "9175393093",
    "address": "3230 Steuben Ave, apt G3",
    "city": "Bronx",
    "state": "NY",
    "zip": "10467",
    "birthdate": "21 Apr 1985 10:10:00 GMT-0400",
    "gender": "Female",
    "ethnicity": "Hispanic",
    "linkedin": "https://google.com",
    "github": "https://github.com/paul",
    "extralink": "https://twitter.com/JohnFajardo",
    "coverletter": "Lorem ipsum dolor sit amet",
    "education": "Bachelors degree in journalism",
    "collegemajor": "Journalism",
    "collegelocation": "Caracas, Venezuela",
    "isemployed": false,
    "employer": "N/A",
    "military": false,
    "income": "$0-$25,000",
    "laptop": true,
    "whyinterested": "Because I need a job",
    "howheard": "Heard in Google",
    "skilllevel": "Intermediate"
    },
    {
    "name": "Jacque",
    "phone": "1234567890",
    "address": "89 Van Vorst Ave",
    "city": "Providence",
    "state": "RI",
    "zip": "19892",
    "birthdate": "2 Feb 1994 10:10:00 GMT-0400",
    "gender": "Female",
    "ethnicity": "Native Amercan",
    "linkedin": "linkedin.com/barbie",
    "github": "https://github.com/jacque",
    "extralink": "https://twitter.com/jacque",
    "coverletter": "Lorem ipsum dolor sit amet",
    "education": "Bachelors",
    "collegemajor": "Racial Studies",
    "collegelocation": "Providence, RI",
    "isemployed": false,
    "employer": "N/A",
    "military": false,
    "income": "$40,000",
    "laptop": true,
    "whyinterested": "Research purposes",
    "howheard": "Friend",
    "skilllevel": "Beginner"
    },


    {
    "name": "Barbie",
    "phone": "1234567890",
    "address": "39 Warner Street",
    "city": "Malibu",
    "state": "CA",
    "zip": "90210",
    "birthdate": "3 May 1993 10:10:00 GMT-0400",
    "gender": "Female",
    "ethnicity": "European",
    "linkedin": "linkedin.com/barbie",
    "github": "https://github.com/barbie",
    "extralink": "https://twitter.com/barbie",
    "coverletter": "Ready to stop the party",
    "education": "Bachelors",
    "collegemajor": "Fashion",
    "collegelocation": "New York, NY",
    "isemployed": true,
    "employer": "instagram",
    "military": false,
    "income": "$70,000",
    "laptop": true,
    "whyinterested": "New Career",
    "howheard": "Matel",
    "skilllevel": "Beginner"
    }
];
